services:
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: koalaq-weaviate-standalone
    restart: unless-stopped
    ports:
      - "10769:8080"
      - "50050:50051"
    volumes:
      - ./weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'false'
      LOG_LEVEL: 'info'
      GOMAXPROCS: '4'
      LIMIT_RESOURCES: 'false'
      GOMEMLIMIT: '2GiB'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
